import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useSelector } from "react-redux";
import api from "../services/api";

function EmployeeList({ showToast }) {
  const { user } = useSelector((state) => state.auth);
  const navigate = useNavigate();

  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // SQL Join overlay state
  const [showJoins, setShowJoins] = useState(false);
  const [joinsData, setJoinsData] = useState(null);
  const [joinsLoading, setJoinsLoading] = useState(false);

  const fetchEmployees = async () => {
    try {
      setLoading(true);
      const res = await api.get("/employees");
      setEmployees(res.data);
    } catch (error) {
      showToast("Failed to load employee list", "error");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEmployees();
  }, []);

  const handleFetchJoins = async () => {
    try {
      setJoinsLoading(true);
      const res = await api.get("/employees/raw-joins");
      setJoinsData(res.data);
      setShowJoins(true);
    } catch (error) {
      showToast("Failed to fetch raw join data", "error");
    } finally {
      setJoinsLoading(false);
    }
  };

  const handleDelete = async (id, name) => {
    if (window.confirm(`Are you sure you want to delete the profile for ${name}?`)) {
      try {
        await api.delete(`/employees/${id}`);
        showToast("Employee profile deleted", "success");
        fetchEmployees();
      } catch (error) {
        showToast("Failed to delete employee profile", "error");
      }
    }
  };

  // Determine editing/deleting permissions
  const canModify = user && (user.role === "admin" || user.role === "manager");

  if (loading) {
    return (
      <div className="dashboard-loading">
        <div className="spinner"></div>
        <p>Loading Employee Directory...</p>
      </div>
    );
  }

  return (
    <div className="employee-list-container animate-fade-in" style={{ width: "100%", padding: "20px" }}>
      <div className="welcome-banner" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "15px" }}>
        <div>
          <h2>👥 Employee Directory</h2>
          <p>Access designations, departments, contact items, skills, and documentation attachments.</p>
        </div>
        <div style={{ display: "flex", gap: "10px" }}>
          <button onClick={handleFetchJoins} className="btn-secondary" style={{ borderColor: "var(--color-primary)", color: "var(--color-primary)" }}>
            🔍 View SQL JOIN Queries
          </button>
          {canModify && (
            <button onClick={() => navigate("/employees/create")} className="btn-primary">
              ➕ Add Employee Profile
            </button>
          )}
        </div>
      </div>

      {/* SQL Joins Modal/Overlay */}
      {showJoins && (
        <div className="joins-modal-overlay" style={{
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: "rgba(15, 23, 42, 0.4)",
          backdropFilter: "blur(4px)",
          zIndex: 1100,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "20px"
        }}>
          <div className="card joins-modal-content animate-fade-in" style={{
            maxWidth: "900px",
            width: "100%",
            maxHeight: "85vh",
            overflowY: "auto",
            position: "relative",
            boxShadow: "var(--shadow-lg)"
          }}>
            <button onClick={() => setShowJoins(false)} style={{
              position: "absolute",
              top: "20px",
              right: "20px",
              background: "transparent",
              border: "none",
              fontSize: "1.5rem",
              cursor: "pointer",
              color: "var(--color-text-muted)"
            }}>&times;</button>

            <h3 style={{ color: "var(--color-primary)", display: "flex", alignItems: "center", gap: "8px" }}>
              📖 Educational SQL JOIN Results
            </h3>
            <p className="card-desc" style={{ marginBottom: "20px" }}>
              Prisma converts Object-Relational queries into standard SQL queries. Below are the actual outputs generated by running the raw INNER JOIN SQL scripts.
            </p>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
              {/* Join 1 Panel */}
              <div style={{ display: "flex", flexDirection: "column" }}>
                <h4 style={{ fontSize: "0.95rem", fontWeight: "700", marginBottom: "8px" }}>Join 1: Users ↔ Departments</h4>
                <div className="token-display" style={{ maxHeight: "120px" }}>
                  <code style={{ fontSize: "0.75rem", color: "var(--color-primary)" }}>{`SELECT u.name, d.department_name
FROM employee_profiles ep
INNER JOIN users u ON ep.user_id = u.id
INNER JOIN departments d ON ep.department_id = d.id;`}</code>
                </div>
                <div className="admin-table-wrapper" style={{ marginTop: "10px", maxHeight: "200px", overflowY: "auto" }}>
                  <table className="admin-table" style={{ width: "100%" }}>
                    <thead>
                      <tr>
                        <th>User Name</th>
                        <th>Department</th>
                      </tr>
                    </thead>
                    <tbody>
                      {joinsData?.join1.length === 0 ? (
                        <tr><td colSpan="2" style={{ textAlign: "center" }}>No rows returned</td></tr>
                      ) : (
                        joinsData?.join1.map((row, idx) => (
                          <tr key={idx}>
                            <td style={{ fontWeight: "600" }}>{row.name}</td>
                            <td>{row.department_name}</td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Join 2 Panel */}
              <div style={{ display: "flex", flexDirection: "column" }}>
                <h4 style={{ fontSize: "0.95rem", fontWeight: "700", marginBottom: "8px" }}>Join 2: Users ↔ Skills</h4>
                <div className="token-display" style={{ maxHeight: "120px" }}>
                  <code style={{ fontSize: "0.75rem", color: "#059669" }}>{`SELECT u.name, s.skill_name
FROM employee_skills es
INNER JOIN employee_profiles ep ON es.employee_id = ep.id
INNER JOIN users u ON ep.user_id = u.id
INNER JOIN skills s ON es.skill_id = s.id;`}</code>
                </div>
                <div className="admin-table-wrapper" style={{ marginTop: "10px", maxHeight: "200px", overflowY: "auto" }}>
                  <table className="admin-table" style={{ width: "100%" }}>
                    <thead>
                      <tr>
                        <th>User Name</th>
                        <th>Skill Name</th>
                      </tr>
                    </thead>
                    <tbody>
                      {joinsData?.join2.length === 0 ? (
                        <tr><td colSpan="2" style={{ textAlign: "center" }}>No rows returned</td></tr>
                      ) : (
                        joinsData?.join2.map((row, idx) => (
                          <tr key={idx}>
                            <td style={{ fontWeight: "600" }}>{row.name}</td>
                            <td>
                              <span className="skill-badge" style={{ padding: "2px 8px", fontSize: "0.75rem", borderRadius: "10px", backgroundColor: "#ecfdf5", color: "#059669", fontWeight: "bold" }}>
                                {row.skill_name}
                              </span>
                            </td>
                          </tr>
                        ))
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Directory Table */}
      <div className="card" style={{ marginTop: "24px" }}>
        {employees.length === 0 ? (
          <div style={{ padding: "40px", textAlign: "center", color: "var(--color-text-muted)" }}>
            <span style={{ fontSize: "3rem" }}>👥</span>
            <h3>No employee profiles created yet.</h3>
            {canModify && <p style={{ marginTop: "5px" }}>Click "Add Employee Profile" above to initialize a record.</p>}
          </div>
        ) : (
          <div className="admin-table-wrapper" style={{ overflowX: "auto" }}>
            <table className="admin-table" style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr style={{ borderBottom: "2px solid var(--color-border)" }}>
                  <th style={{ padding: "12px" }}>ID</th>
                  <th style={{ padding: "12px" }}>Employee</th>
                  <th style={{ padding: "12px" }}>Corporate Details</th>
                  <th style={{ padding: "12px" }}>Salary & Contact</th>
                  <th style={{ padding: "12px" }}>Assigned Skills</th>
                  <th style={{ padding: "12px" }}>Attachments</th>
                  {canModify && <th style={{ padding: "12px", textAlign: "center" }}>Actions</th>}
                </tr>
              </thead>
              <tbody>
                {employees.map((emp) => (
                  <tr key={emp.id} style={{ borderBottom: "1px solid var(--color-border)", verticalAlign: "top" }}>
                    {/* ID */}
                    <td style={{ padding: "14px 12px", fontFamily: "var(--font-mono)", fontSize: "0.85rem" }}>{emp.id}</td>
                    
                    {/* User info */}
                    <td style={{ padding: "14px 12px" }}>
                      <strong style={{ display: "block", color: "var(--color-text-main)", fontSize: "0.95rem" }}>{emp.user.name}</strong>
                      <span style={{ display: "block", color: "var(--color-text-muted)", fontSize: "0.82rem" }}>{emp.user.email}</span>
                      <span className="user-role-badge" style={{
                        marginTop: "4px",
                        fontSize: "0.7rem",
                        padding: "2px 6px",
                        backgroundColor: "#f1f5f9",
                        borderRadius: "4px",
                        display: "inline-block"
                      }}>{emp.user.role.toUpperCase()}</span>
                    </td>

                    {/* Corporate Details */}
                    <td style={{ padding: "14px 12px" }}>
                      <strong style={{ display: "block", color: "var(--color-text-main)" }}>{emp.designation}</strong>
                      <span style={{ display: "block", color: "var(--color-primary)", fontWeight: "600", fontSize: "0.85rem" }}>
                        🏢 {emp.department.departmentName}
                      </span>
                    </td>

                    {/* Salary & Contact */}
                    <td style={{ padding: "14px 12px" }}>
                      <span style={{ display: "block", fontWeight: "600", color: "#1e293b", fontSize: "0.9rem" }}>
                        ${parseFloat(emp.salary).toLocaleString("en-US", { minimumFractionDigits: 2 })}
                      </span>
                      <span style={{ display: "block", fontSize: "0.8rem", color: "var(--color-text-muted)", marginTop: "2px" }}>
                        📞 {emp.phone}
                      </span>
                      <span style={{ display: "block", fontSize: "0.75rem", color: "var(--color-text-muted)", marginTop: "2px" }} title={emp.address}>
                        📍 {emp.address.length > 25 ? emp.address.substring(0, 25) + "..." : emp.address}
                      </span>
                    </td>

                    {/* Assigned Skills */}
                    <td style={{ padding: "14px 12px" }}>
                      <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", maxWidth: "180px" }}>
                        {emp.skills.length === 0 ? (
                          <span style={{ color: "var(--color-text-muted)", fontSize: "0.8rem" }}>None</span>
                        ) : (
                          emp.skills.map((s) => (
                            <span key={s.id} className="skill-badge" style={{
                              padding: "2px 6px",
                              backgroundColor: "var(--color-primary-light)",
                              color: "var(--color-primary)",
                              borderRadius: "10px",
                              fontSize: "0.72rem",
                              fontWeight: "bold"
                            }}>
                              {s.skill.skillName}
                            </span>
                          ))
                        )}
                      </div>
                    </td>

                    {/* Images / Credentials list */}
                    <td style={{ padding: "14px 12px" }}>
                      <div style={{ display: "flex", gap: "6px" }}>
                        {emp.images.length === 0 ? (
                          <span style={{ color: "var(--color-text-muted)", fontSize: "0.8rem" }}>No files</span>
                        ) : (
                          emp.images.map((img) => (
                            <a
                              key={img.id}
                              href={img.imageUrl}
                              target="_blank"
                              rel="noreferrer"
                              className="employee-img-thumb"
                              style={{
                                display: "block",
                                width: "32px",
                                height: "32px",
                                borderRadius: "4px",
                                overflow: "hidden",
                                border: "1px solid var(--color-border)",
                                cursor: "zoom-in"
                              }}
                              title="Click to view file"
                            >
                              <img src={img.imageUrl} alt="doc" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                            </a>
                          ))
                        )}
                      </div>
                    </td>

                    {/* Actions column */}
                    {canModify && (
                      <td style={{ padding: "14px 12px" }}>
                        <div style={{ display: "flex", gap: "8px", justifyContent: "center" }}>
                          <button
                            onClick={() => navigate(`/employees/edit/${emp.id}`)}
                            className="btn-secondary"
                            style={{ padding: "4px 8px", fontSize: "0.75rem" }}
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => handleDelete(emp.id, emp.user.name)}
                            className="btn-secondary"
                            style={{ padding: "4px 8px", fontSize: "0.75rem", borderColor: "var(--color-error)", color: "var(--color-error)" }}
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    )}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default EmployeeList;
